### ISSUE TITLE
Any chance to compile it for Win?

### ISSUE THREAD

**Issue by AngryPhantom** [kmatveev/zx-sof-reveng#1]
Hello,

Soldier of Fortune was my all time favorite game when I was a kid! Any chance to compile it for Windows? Or, maybe, you know where to get the binary if it's available?

Also, if the above is impossible, do you know a decent emulator that allows to change the keybindings for this game? I've tried many of them and ZXSpin seems to be the best one, but I cannot change them (the default keybindings are a bit weird on a PC keyboard).

TIA

**Comment by kmatveev** [comment]
> Any chance to compile it for Windows? Or, maybe, you know where to get the binary if it's available?

This task is too complex for me, I only hope to obtain some meaningful understanding of how it works.


> Also, if the above is impossible, do you know a decent emulator that allows to change the keybindings for this game? I've tried many of them and ZXSpin seems to be the best one, but I cannot change them (the default keybindings are a bit weird on a PC keyboard).

Yes, this is possible. In game's main menu press "Enter" to change controls, possible options are "keyboard" (default), "sinclair", "kempston" and "cursor". I suggest selecting "cursor". ZXSpin by default maps Windows cursor keys to ZX Spectrum cursor keys. Also Ctrl is mapped to "0" so you can use it as a "fire" button.

**Comment by AngryPhantom** [comment]
> press "Enter" to change controls. I suggest selecting "cursor".

Oh my god, that was really easy. I tried changing keybindings in the ZXSpin settings actually, but never chose Cursor from the game. Thank you very much!
